### ISSUE TITLE
Error messages changed breaking shoulda tests

### ISSUE THREAD

**Issue by pupeno** [mutoh/gettext_activerecord#1]
Error messages, after including gettext_activerecord changed breaking many shoulda tests, with this message:

> Expected errors to include "can't be blank" when name is set to nil, got errors: name Name can't be blank (nil)

I believe I understand why you made that change and that it is a good thing; but maybe you could monkey-patch shoulda in this gem so that it works transparently.

Thanks.

**Comment by mutoh** [comment]
If we keep to work transparently, you didn't change your code.
It doesn't work with your code, so you change your code what I hope.

Unfortunately, Rails-i18n people doesn't take care of the languages which doesn't have S+V+O grammer.

**Comment by pupeno** [comment]
I don't understand your point. I understand why what you did is the way to go. There's a third party library, shoulda, which depends on the error messages being the way Rails without gettext_activerecord works. I think gettetx_activerecord could monkey-patch that library so everything continues to work transparently after starting using either or both together.
